[project]
name = 'welsh-street'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST3Q0826K15YSHP5GTFJ3CW347JQRM0E1FENT6XWD.welshcorgicoin'

[contracts.comptroller]
path = 'contracts/comptroller.clar'
clarity_version = 3
epoch = 'latest'

[contracts.credit]
path = 'contracts/credit.clar'
clarity_version = 3
epoch = 'latest'

[contracts.exchange]
path = 'contracts/exchange.clar'
clarity_version = 3
epoch = 'latest'

[contracts.genesis]
path = 'contracts/genesis.clar'
clarity_version = 3
epoch = 'latest'

[contracts.rewards]
path = 'contracts/rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.street]
path = 'contracts/street.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'